---
title: "Children’s Vocabulary Development in American Sign Language"
subtitle: "Similar Trends in Developing Vocabulary for Sign Language and Speech Language"
author: Aliyah Maxine Ramos
thanks: "Code and data are available at: https://github.com/mxnrms/Children_Vocab_Development.git."
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "This paper investigates the cognitive development of American Sign Language in children by observing the relationship between different ages during developmental years and the various types of vocabulary terms. Using the data from the open database, Wordbank, we found that children learning to speak a visual language share a similar trend in vocabulary development to those learning auditory languages. This highlights the importance of learning American Sign Language at an early age as it provides the ability for those with hearing impairments or disabilities to participate in society like any other able-bodied individual."
format: 
  pdf:
    documentclass: article
number-sections: true
bibliography: references.bib
---

# Introduction

American Sign Language (ASL) allows for communication and interaction with the community of people who are deaf or have hearing disabilities. This makes sign language an essential tool for inclusivity and accessibility. Learning ASL enables those with hearing impairments to participate in society just like any other abled person. The ability to communicate with others through ASL can help diminish communication barriers and help create more inclusive environments for all. And learning languages is best at early stages of life.

In this paper, we investigate the patterns and trends that occur during the early developmental years of childhood in terms of vocabulary in American Sign Language. The estimand that we are trying to estimate is the relationship between children's developmental ages and their comprehension and production of vocabulary words in American Sign Language. We wanted to visualize the milestones for children's vocabulary development in sign language to ultimately compare it to the timeline of vocabulary development for speech-language. This paper uses data obtained from the open database, Wordbank, which exhibits information on the development of children's vocabulary in various languages. The dataset, "Full Child-by-Word", provides information on variables affecting the development of a child's vocabulary for a specific language. The variables include details about the child, including age, details about the vocabulary words, and how the child assesses each term.

With our focus on the development of American Sign Language vocabulary, we found that children learning to communicate a visual language share similar trends in vocabulary development to those that are learning a spoken language. We were also interested in how children develop this natural language at an early age and the differences in comprehension and production between different vocabulary terms. The findings in this paper highlight the importance of learning American Sign Language at an early age because it allows those with hearing disabilities to experience a more accessible world. By understanding the cognitive processes involved in learning a visual language, we are better able to support individuals in their language acquisition.

The remainder of this paper is structured as follows: @sec-data introduces the data used for analysis and findings, including visualizations of the variables of interest, @sec-model presents the simple linear regression model to justify and predict the relationship between the developmental ages of children and their comprehension and production of vocabulary words in ASL, @sec-results displays the interpretations of the model alongside other findings from analyzing the data, and @sec-discussion provides a discussion on the ways in which the findings apply to the real world as well as the weaknesses of the paper and its next steps for further study on this subject.

# Data {#sec-data}

## Overview of Data {#sec-overview-of-data}

### Data Source {#sec-data-source}

### Variables of Interest {#sec-variables-of-interest}

# Model {#sec-model}

# Results {#sec-results}

# Discussion {#sec-discussion}

## First discussion point {#sec-first-point}

## Second discussion point {#sec-second-point}

## Third discussion point {#sec-third-point}

## Weaknesses & Next Steps {#sec-weaknesses-next-steps}

### Weaknesses {#sec-weaknesses}

### Next Steps {#sec-next-steps}

\newpage

\appendix

# Appendix {.unnumbered}

# Additional details {#sec-additional-details}

\newpage

# References {#sec-references}
